name: Checks for quel_ic_config (without devices)

on:
  pull_request:
    paths:
      - "quel_ic_config/**"
  push:
    branches:
      - "main"
      - "maintenance/**"
jobs:
  checks-and-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: quel_ic_config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --extra dev

      - name: Validate json
        run: make validate-json

      - name: Run linter
        run: make lint
        env:
          RUFF_OUTPUT_FORMAT: github
        if: ${{ !cancelled() }}

      - name: Check format (python)
        run: make format-py
        env:
          RUFF_OUTPUT_FORMAT: github
        if: ${{ !cancelled() }}

      - name: Check format (cpp)
        run: make format-cpp
        if: ${{ !cancelled() }}

      - name: Run typechecker
        run: make typecheck
        if: ${{ !cancelled() }}

      - name: Run tests without devices
        run: |
          sudo mkdir /run/quelware # for file lock
          make test-without-devices
        if: ${{ !cancelled() }}
